version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: complex_python_app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
